#!/bin/bash
[[ "$1" == "final" ]] || exit 0
set -xeuo pipefail

LSB_RELEASE=trusty
SSH_TARGET="apt-upload@apt.ec2.shopify.com"
APPNAME="$(cat /app/APPNAME)"
test "${APPNAME}"

cleanup() {
  sudo rm -rf ~/.ssh
}
trap cleanup EXIT

setup_ssh_keys() {
  mkdir -p ~/.ssh
  ruby -rjson -e 'puts JSON.load(File.read("/app/config/secrets.json"))["privkey"]' > ~/.ssh/id_rsa
  ruby -rjson -e 'puts JSON.load(File.read("/app/config/secrets.json"))["pubkey"]' > ~/.ssh/id_rsa.pub
  echo "apt.ec2.shopify.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF7qYvPBGkhIJeeLWz9Po+WrjwrpGKwuiadkR/MCeh1Xx5tEIuDghaFC3QvMQesOHMts+n44gdjsqz9Kwqe4suLNTA8bVdrwD1bWO/nJNsRdfnyKrXWU7GVl2d/8kspKXZuVhOb+O9/gPallhLFmFZL/YAaL4jVOF8tI/12B0hVzYkrk4Y2ePujT9edaPQD/XNWE3102VFyEgfqZm96puhzDk51ZfcKtsHfIqwwILLe9KlORF66URMV6QFmt0ls4hSbtRhHH0wjJAkHBdkK6jow0QN8tkPjU0Qxuxdea8YBioKDfnWBltggQM6RhjLu+amyR3oIGdyXz4pyYRJp85X" \
    > ~/.ssh/known_hosts
  chmod 0600 ~/.ssh/id_rsa
}

build_deb() {
  make dev_bootstrap all
}

genchanges() {
  (
    cd pkg
    /app/borg/fpm2changes "${LSB_RELEASE}" *.deb > "${APPNAME}.changes"
  )
}

inspect() {
  dpkg-deb --contents /app/pkg/*.deb
  cat /app/pkg/*.changes
}

generate_upload_id() {
  ts="$(date +"%Y%m%d_%H%M%S")"
  un=locutus
  hn="$(hostname | sed 's/\..*//')"
  pid=$$
  echo "${ts}_${un}_${hn}_${pid}_${RANDOM}"
}

upload_deb() {
  upload_id="$(generate_upload_id)"
  final_path="/data/uploads/pending/${upload_id}"
  temp_path="${final_path}.tmp"
  rsync_target="${ssh_target}:${temp_path}/"

  rsync -dtP /app/pkg/ "${rsync_target}"
  ssh "${ssh_target}" "mv '${temp_path}' '${final_path}'"
}

main() {
  setup_ssh_keys
  build_deb
  genchanges
  inspect
  #upload_deb
}
main "$@"

