#!/bin/bash
set -xeuo pipefail

LSB_RELEASE="lucid"
APPNAME="$(cat /app/APPNAME)"
test "${APPNAME}"

cleanup() {
  sudo rm -rf /workspace
}
trap cleanup EXIT

gen_version() {
  local version="$(cat /app/VERSION)"
  local revision="$(cat /app/REVISION)"
  test "${version}"
  test "${revision}"
  echo "${version}-${revision:0:8}" # eg: 1.0-deadbeef
}

setup_workspace() {
  sudo mkdir /workspace
  sudo chown -R borg:borg /workspace
  cp -a /app "/workspace/${APPNAME}"
}

install_build_deps() {
  cd "/workspace/${APPNAME}/debian"
  mk-build-deps control
  sudo dpkg -i *.deb || true
  sudo apt-get -f -y install
}

build_deb() {
  local version=$1;shift
  cd "/workspace/${APPNAME}/debian"

  dch \
    --newversion "${version}" \
    --force-bad-version \
    -D "${LSB_RELEASE}" \
    "Release for ${LSB_RELEASE}"

  debuild -i -us -uc -b
}

inspect() {
  ls -lsa /workspace
  sudo dpkg -i /workspace/*.deb
  cat /workspace/*.changes
  dpkg-query -L "${APPNAME}"
  man "${APPNAME}"
}

main() {
  local version="$(gen_version)"
  setup_workspace
  install_build_deps
  build_deb "${version}"
  inspect
}
main "$@"

