#!/bin/bash
set -euo pipefail

distro=$1;shift
deb=$1;shift
test "${deb}"
test "${distro}"

dir=$(mktemp -d)
trap 'rm -rf "${dir}"' EXIT

cp "${deb}" "${dir}"
cd "${dir}"

ar vx *.deb > /dev/null
tar xf control.tar.gz
tar xf data.tar.gz
cat usr/share/doc/*/changelog.Debian.gz | zcat > changelog

pkgname=$(grep -oP "(?<=Package: )(.*)" control)
echo "Source: ${pkgname}" >> control

dpkg-genchanges -lchangelog -ccontrol -u. -f<(echo *.deb admin extra) -b -q "-DDistribution=${distro}" 2>/dev/null
