#!/bin/bash
set -xeuo pipefail

apt-get update
apt-get install -y --no-install-recommends \
  build-essential \
  equivs \
  devscripts \
  openssh-server

echo "borg ALL = NOPASSWD: ALL" > /etc/sudoers.d/borg-needs-sudo
