#!/bin/bash
set -euo pipefail

distro=$1;shift
deb=$1;shift
test "${deb}"
test "${distro}"

GREP=$(which ggrep || which grep)
if [[ -n $(${GREP} --version | ${GREP} BSD) ]] ; then
	echo "To run this on OS X, you'll have to 'brew install coreutils'" >&2
	exit 1
fi

if [[ -z $(which dpkg-genchanges) ]]; then
	echo "You unfortunately will need dpkg-genchanges to run this." >&2
	echo "On debian/ubuntu: apt-get install devscripts" >&2
	echo "On OS X: brew install debianutils (maybe? I'm on a plane and I'll probably forget to update this after.)" >&2
	exit 1
fi

dir=$(mktemp -d /tmp/fpm2changesXXXXXX)
trap 'rm -rf "${dir}"' EXIT

cp "${deb}" "${dir}"
cd "${dir}"

ar x *.deb
tar xf control.tar.gz
tar xf data.tar.gz
cat usr/share/doc/*/changelog.Debian.gz | zcat > changelog

pkgname=$(${GREP} -oP "(?<=Package: )(.*)" control)
echo "Source: ${pkgname}" >> control

dpkg-genchanges -lchangelog -ccontrol -u. -f<(echo *.deb admin extra) -b -q "-DDistribution=${distro}" "-DBinary=${pkgname}" 2>/dev/null
